version: '3.3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    command: mix phoenix.server
    environment:
      MIX_ENV: dev
      PORT: 4000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:9.5.4
    volumes:
      - ./volumes/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db